spring.application.name=TTIKU
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TTIKUS;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jackson.serialization.indent_output=true
spring.jackson.visibility.field=any
spring.jackson.visibility.getter=any
spring.jackson.serialization.fail-on-empty-beans=false